name: Scan Boursier Quotidien

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0-6'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les outils boursiers
        run: |
          pip install --upgrade pip
          # On installe uniquement ce que requiert votre serveur Emergent
          pip install numpy pandas yfinance requests resend

      - name: Lancer le calcul
        run: python backend/server.py  # Modifié pour cibler server.py
