name: Scan Boursier Quotidien

on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * 0-6'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Fixé sur la version stable 3.10

      - name: Installer les outils boursiers
        run: |
          pip install --upgrade pip
          pip install numpy==1.23.5 pandas==1.5.3 yfinance requests resend
          pip install pandas-ta --no-dependencies # Force l'installation de pandas-ta sans blocage

      - name: Lancer le calcul
        run: python backend/main.py
